### ISSUE TITLE
Isochrone calculation fails

### ISSUE THREAD

**Issue by rastrau** [ebp-group/walkalytics-clients#3]
Python tool `Isochrone` fails with the following error message (ArcGIS 10.3):

`Traceback (most recent call last):`
`File "<string>", line 183, in execute`
`TypeError: object() takes no parameters`
`Failed to execute (Isochrone).`

Maybe mixed indentation characters or some other quirky Python error.

**Comment by ping13** [comment]
can't reproduce this (however, I pushed a long pending update to the code this morning).

- Are the dependencies satisfied (namely PIL)?
- What is the input?

![image](https://cloud.githubusercontent.com/assets/108406/13984574/6fe61178-f0f7-11e5-914b-594bc5757c32.png)

**Comment by rastrau** [comment]
Okay, re-cloned repo, but error persists.
Inputs: 
![temp](https://cloud.githubusercontent.com/assets/4510815/13984848/2ab440dc-f0f9-11e5-8322-798de5d1f4dd.png)

Pillow was installed from wheel as described in https://github.com/ernstbaslerpartner/walkalytics-clients#arcgis-desktop. Point FGDB FC is used as input (V:\rsm\temp\Inputdaten.zip).

**Comment by ping13** [comment]
Seems to be a problem with the FC: The code in line [205](https://github.com/ernstbaslerpartner/walkalytics-clients/blob/master/ArcGIS-Desktop/walkalytics.pyt#L205) cannot access the coordinates of the point FC.

**Comment by rastrau** [comment]
Just re-tested with newly created LV03 and WGS1984 point FCs with the same result.
Maybe `datatype="GPFeatureRecordSetLayer"` won't work with FCs (dunno that datatype)?

(Also bit surprising: `inFeatures = parameters[0].valueAsText` rather than `inFeatures = parameters[0].value`)

**Comment by ping13** [comment]
Bei mir läuft der Prozess durch :-O, die Ergebnisse habe ich mal unter `V:\RSM\TEMP` abgelegt. Ich muss mir das wohl mal an Deinem PC anschauen.
